import { Patient, HealthProfessional, Appointment, MedicalRecord, Prescription, Evaluation, ProgressReport } from '../types';

export const mockPatients: Patient[] = [
  {
    id: '1',
    name: 'Lucas Oliveira Santos',
    dateOfBirth: '2015-03-12',
    cpf: '123.456.789-00',
    responsible: 'Maria Santos',
    responsibleContact: '(11) 98765-4321',
    cid: 'F84.0',
    cidDescription: 'Autismo Infantil',
    address: 'Rua das Flores, 123 - São Paulo, SP',
    phone: '(11) 98765-4321',
  },
  {
    id: '2',
    name: 'Ana Paula Costa',
    dateOfBirth: '2018-07-22',
    cpf: '987.654.321-00',
    responsible: 'João Costa',
    responsibleContact: '(11) 97654-3210',
    cid: 'G80.0',
    cidDescription: 'Paralisia Cerebral Espástica',
    address: 'Av. Principal, 456 - São Paulo, SP',
    phone: '(11) 97654-3210',
  },
  {
    id: '3',
    name: 'Pedro Henrique Silva',
    dateOfBirth: '2016-11-08',
    cpf: '456.789.123-00',
    responsible: 'Carla Silva',
    responsibleContact: '(11) 96543-2109',
    cid: 'Q90',
    cidDescription: 'Síndrome de Down',
    address: 'Rua Verde, 789 - São Paulo, SP',
    phone: '(11) 96543-2109',
  },
  {
    id: '4',
    name: 'Sofia Rodrigues',
    dateOfBirth: '2017-05-15',
    cpf: '321.654.987-00',
    responsible: 'Ana Rodrigues',
    responsibleContact: '(11) 95432-1098',
    cid: 'F80.1',
    cidDescription: 'Distúrbio Expressivo de Linguagem',
    address: 'Rua Azul, 321 - São Paulo, SP',
    phone: '(11) 95432-1098',
  },
  {
    id: '5',
    name: 'Gabriel Ferreira Souza',
    dateOfBirth: '2014-09-20',
    cpf: '789.123.456-00',
    responsible: 'Renata Ferreira',
    responsibleContact: '(11) 94321-0987',
    cid: 'F84.0, F90.0, G40.9',
    cidDescription: 'Autismo Infantil, TDAH (Transtorno de Déficit de Atenção/Hiperatividade), Epilepsia não especificada',
    address: 'Rua dos Lírios, 567 - São Paulo, SP',
    phone: '(11) 94321-0987',
  },
];

export const mockProfessionals: HealthProfessional[] = [
  {
    id: '1',
    name: 'Dr. Roberto Almeida',
    specialty: 'Neurologista Pediátrico',
    crm: 'CRM-SP 123456',
    email: 'roberto.almeida@apae.org',
  },
  {
    id: '2',
    name: 'Dra. Fernanda Lima',
    specialty: 'Fisioterapeuta',
    crm: 'CREFITO-3 45678',
    email: 'fernanda.lima@apae.org',
  },
  {
    id: '3',
    name: 'Dra. Juliana Mendes',
    specialty: 'Fonoaudióloga',
    crm: 'CRFa 2-12345',
    email: 'juliana.mendes@apae.org',
  },
  {
    id: '4',
    name: 'Dr. Carlos Eduardo',
    specialty: 'Psicólogo',
    crm: 'CRP 06/98765',
    email: 'carlos.eduardo@apae.org',
  },
  {
    id: '5',
    name: 'Dra. Patricia Santos',
    specialty: 'Terapeuta Ocupacional',
    crm: 'CREFITO-3 67890',
    email: 'patricia.santos@apae.org',
  },
  {
    id: '6',
    name: 'Dr. Marcos Vieira',
    specialty: 'Neurologista Pediátrico, Psiquiatra Infantil',
    crm: 'CRM-SP 234567 / CRM-SP 234568',
    email: 'marcos.vieira@apae.org',
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: '1',
    patientId: '1',
    patientName: 'Lucas Oliveira Santos',
    professionalId: '4',
    professionalName: 'Dr. Carlos Eduardo',
    date: '2025-11-01',
    time: '09:00',
    status: 'in-progress',
    type: 'Avaliação Psicológica',
  },
  {
    id: '2',
    patientId: '2',
    patientName: 'Ana Paula Costa',
    professionalId: '2',
    professionalName: 'Dra. Fernanda Lima',
    date: '2025-11-01',
    time: '10:30',
    status: 'scheduled',
    type: 'Fisioterapia',
  },
  {
    id: '3',
    patientId: '3',
    patientName: 'Pedro Henrique Silva',
    professionalId: '3',
    professionalName: 'Dra. Juliana Mendes',
    date: '2025-11-01',
    time: '14:00',
    status: 'scheduled',
    type: 'Fonoaudiologia',
  },
  {
    id: '4',
    patientId: '4',
    patientName: 'Sofia Rodrigues',
    professionalId: '3',
    professionalName: 'Dra. Juliana Mendes',
    date: '2025-11-01',
    time: '15:30',
    status: 'scheduled',
    type: 'Terapia da Fala',
  },
  {
    id: '5',
    patientId: '1',
    patientName: 'Lucas Oliveira Santos',
    professionalId: '1',
    professionalName: 'Dr. Roberto Almeida',
    date: '2025-11-03',
    time: '11:00',
    status: 'scheduled',
    type: 'Consulta Neurológica',
  },
  {
    id: '6',
    patientId: '2',
    patientName: 'Ana Paula Costa',
    professionalId: '5',
    professionalName: 'Dra. Patricia Santos',
    date: '2025-11-04',
    time: '09:30',
    status: 'scheduled',
    type: 'Terapia Ocupacional',
  },
  {
    id: '7',
    patientId: '5',
    patientName: 'Gabriel Ferreira Souza',
    professionalId: '6',
    professionalName: 'Dr. Marcos Vieira',
    date: '2025-11-05',
    time: '10:00',
    status: 'scheduled',
    type: 'Avaliação Neuropsiquiátrica',
  },
  {
    id: '8',
    patientId: '5',
    patientName: 'Gabriel Ferreira Souza',
    professionalId: '4',
    professionalName: 'Dr. Carlos Eduardo',
    date: '2025-11-06',
    time: '14:30',
    status: 'scheduled',
    type: 'Psicoterapia',
  },
  // Consultas passadas para histórico
  {
    id: '9',
    patientId: '1',
    patientName: 'Lucas Oliveira Santos',
    professionalId: '4',
    professionalName: 'Dr. Carlos Eduardo',
    date: '2025-10-25',
    time: '09:00',
    status: 'completed',
    type: 'Avaliação Psicológica',
  },
  {
    id: '10',
    patientId: '2',
    patientName: 'Ana Paula Costa',
    professionalId: '2',
    professionalName: 'Dra. Fernanda Lima',
    date: '2025-10-28',
    time: '10:30',
    status: 'completed',
    type: 'Fisioterapia',
  },
  {
    id: '11',
    patientId: '3',
    patientName: 'Pedro Henrique Silva',
    professionalId: '3',
    professionalName: 'Dra. Juliana Mendes',
    date: '2025-10-20',
    time: '14:00',
    status: 'completed',
    type: 'Fonoaudiologia',
  },
  {
    id: '12',
    patientId: '5',
    patientName: 'Gabriel Ferreira Souza',
    professionalId: '6',
    professionalName: 'Dr. Marcos Vieira',
    date: '2025-10-22',
    time: '10:00',
    status: 'completed',
    type: 'Avaliação Neuropsiquiátrica',
  },
];

export const mockMedicalRecords: MedicalRecord[] = [
  {
    id: '1',
    patientId: '1',
    appointmentId: '9',
    professionalId: '4',
    professionalName: 'Dr. Carlos Eduardo',
    date: '2025-10-25',
    symptoms: 'Dificuldade de interação social, comportamentos repetitivos',
    diagnosis: 'Transtorno do Espectro Autista - Nível 2',
    treatment: 'Terapia comportamental, intervenção ABA, acompanhamento psicológico semanal',
    observations: 'Paciente apresentou melhora significativa na comunicação não-verbal. Família está engajada no tratamento.',
    vitalSigns: {
      weight: 22,
      height: 115,
      heartRate: 85,
    },
  },
  {
    id: '2',
    patientId: '2',
    appointmentId: '10',
    professionalId: '2',
    professionalName: 'Dra. Fernanda Lima',
    date: '2025-10-28',
    symptoms: 'Rigidez muscular, dificuldade de movimento',
    diagnosis: 'Paralisia Cerebral Espástica - GMFCS nível III',
    treatment: 'Fisioterapia motora 3x/semana, alongamentos, exercícios de fortalecimento',
    observations: 'Evolução positiva na amplitude de movimento. Recomenda-se continuidade do tratamento.',
    vitalSigns: {
      weight: 18,
      height: 102,
      heartRate: 90,
    },
  },
  {
    id: '3',
    patientId: '3',
    appointmentId: '11',
    professionalId: '3',
    professionalName: 'Dra. Juliana Mendes',
    date: '2025-10-20',
    symptoms: 'Atraso na fala, dificuldade de articulação',
    diagnosis: 'Atraso de linguagem associado à Síndrome de Down',
    treatment: 'Fonoterapia 2x/semana, exercícios de linguagem oral',
    observations: 'Paciente está mais comunicativo. Vocabulário expandiu de 50 para 80 palavras.',
    vitalSigns: {
      weight: 25,
      height: 108,
    },
  },
  {
    id: '4',
    patientId: '5',
    appointmentId: '12',
    professionalId: '6',
    professionalName: 'Dr. Marcos Vieira',
    date: '2025-10-22',
    symptoms: 'Hiperatividade, dificuldade de concentração, comportamentos repetitivos, crises convulsivas ocasionais',
    diagnosis: 'Comorbidade: TEA (F84.0) + TDAH (F90.0) + Epilepsia (G40.9)',
    treatment: 'Terapia comportamental intensiva, metilfenidato para TDAH, anticonvulsivante (ácido valproico), acompanhamento neuropsiquiátrico mensal',
    observations: 'Paciente apresenta quadro complexo com múltiplas condições. Família bem orientada sobre medicação e rotinas. Última crise epilética há 3 meses. Atenção redobrada na escola e terapias.',
    vitalSigns: {
      weight: 35,
      height: 128,
      heartRate: 88,
      bloodPressure: '105/65',
    },
  },
];

export const mockPrescriptions: Prescription[] = [
  {
    id: '1',
    patientId: '1',
    patientName: 'Lucas Oliveira Santos',
    professionalId: '1',
    professionalName: 'Dr. Roberto Almeida',
    date: '2025-10-15',
    medications: [
      {
        name: 'Risperidona',
        dosage: '0.5mg',
        frequency: '1x ao dia (à noite)',
        duration: '60 dias',
      },
    ],
    validUntil: '2025-12-14',
    status: 'active',
    renewalRequested: false,
  },
  {
    id: '2',
    patientId: '2',
    patientName: 'Ana Paula Costa',
    professionalId: '2',
    professionalName: 'Dra. Fernanda Lima',
    date: '2025-09-10',
    medications: [
      {
        name: 'Baclofeno',
        dosage: '5mg',
        frequency: '2x ao dia',
        duration: '90 dias',
      },
    ],
    validUntil: '2025-12-09',
    status: 'active',
    renewalRequested: true,
    renewalRequestedDate: '2025-11-01',
  },
  {
    id: '3',
    patientId: '1',
    patientName: 'Lucas Oliveira Santos',
    professionalId: '4',
    professionalName: 'Dr. Carlos Eduardo',
    date: '2025-08-20',
    medications: [
      {
        name: 'Melatonina',
        dosage: '3mg',
        frequency: '1x ao dia (antes de dormir)',
        duration: '30 dias',
      },
    ],
    validUntil: '2025-11-15',
    status: 'expiring_soon',
    renewalRequested: false,
  },
  {
    id: '4',
    patientId: '5',
    patientName: 'Gabriel Ferreira Souza',
    professionalId: '6',
    professionalName: 'Dr. Marcos Vieira',
    date: '2025-10-01',
    medications: [
      {
        name: 'Ácido Valproico (Depakene)',
        dosage: '250mg',
        frequency: '2x ao dia (manhã e noite)',
        duration: '90 dias',
      },
      {
        name: 'Metilfenidato (Ritalina)',
        dosage: '10mg',
        frequency: '2x ao dia (após café da manhã e almoço)',
        duration: '90 dias',
      },
      {
        name: 'Risperidona',
        dosage: '1mg',
        frequency: '1x ao dia (à noite)',
        duration: '90 dias',
      },
    ],
    validUntil: '2025-12-30',
    status: 'active',
    renewalRequested: false,
    observations: 'Paciente com comorbidades (TEA + TDAH + Epilepsia). Monitorar efeitos colaterais. Não suspender medicações abruptamente. Retorno mensal obrigatório.',
  },
];

export const mockEvaluations: Evaluation[] = [
  {
    id: '1',
    patientId: '1',
    patientName: 'Lucas Oliveira Santos',
    appointmentId: '1',
    professionalId: '4',
    professionalName: 'Dr. Carlos Eduardo',
    date: '2025-10-26',
    rating: 5,
    comment: 'Excelente profissional! Muito atencioso com meu filho. Notamos grande evolução.',
    category: 'professional',
  },
  {
    id: '2',
    patientId: '2',
    patientName: 'Ana Paula Costa',
    appointmentId: '2',
    professionalId: '2',
    professionalName: 'Dra. Fernanda Lima',
    date: '2025-10-29',
    rating: 5,
    comment: 'A fisioterapia tem ajudado muito! A Dra. Fernanda é maravilhosa.',
    category: 'professional',
  },
  {
    id: '3',
    patientId: '3',
    patientName: 'Pedro Henrique Silva',
    appointmentId: '3',
    professionalId: '3',
    professionalName: 'Dra. Juliana Mendes',
    date: '2025-10-21',
    rating: 4,
    comment: 'Ótimo atendimento, porém a sala de espera estava um pouco cheia.',
    category: 'service',
  },
  {
    id: '4',
    patientId: '4',
    patientName: 'Sofia Rodrigues',
    appointmentId: '4',
    professionalId: '3',
    professionalName: 'Dra. Juliana Mendes',
    date: '2025-10-22',
    rating: 5,
    comment: 'Minha filha adorou a sessão! A fonoaudióloga é muito carinhosa e paciente.',
    category: 'professional',
  },
  {
    id: '5',
    patientId: '1',
    patientName: 'Lucas Oliveira Santos',
    appointmentId: '5',
    professionalId: '1',
    professionalName: 'Dr. Roberto Almeida',
    date: '2025-10-18',
    rating: 5,
    comment: 'Dr. Roberto é excepcional! Explica tudo com clareza e nos deixa tranquilos.',
    category: 'professional',
  },
  {
    id: '6',
    patientId: '2',
    patientName: 'Ana Paula Costa',
    appointmentId: '6',
    professionalId: '5',
    professionalName: 'Dra. Patricia Santos',
    date: '2025-10-15',
    rating: 4,
    comment: 'Bom atendimento. A terapia ocupacional está ajudando nas atividades diárias.',
    category: 'professional',
  },
  {
    id: '7',
    patientId: '3',
    patientName: 'Pedro Henrique Silva',
    appointmentId: '3',
    professionalId: '4',
    professionalName: 'Dr. Carlos Eduardo',
    date: '2025-10-12',
    rating: 5,
    comment: 'Psicólogo maravilhoso! Consegue conectar muito bem com meu filho.',
    category: 'professional',
  },
  {
    id: '8',
    patientId: '1',
    patientName: 'Lucas Oliveira Santos',
    appointmentId: '1',
    professionalId: '2',
    professionalName: 'Dra. Fernanda Lima',
    date: '2025-10-10',
    rating: 3,
    comment: 'Atendimento bom, mas a consulta foi mais rápida que o esperado.',
    category: 'service',
  },
  {
    id: '9',
    patientId: '4',
    patientName: 'Sofia Rodrigues',
    appointmentId: '4',
    professionalId: '5',
    professionalName: 'Dra. Patricia Santos',
    date: '2025-10-08',
    rating: 5,
    comment: 'Instalações limpas e acolhedoras. Ambiente muito adequado para as crianças.',
    category: 'facilities',
  },
  {
    id: '10',
    patientId: '2',
    patientName: 'Ana Paula Costa',
    appointmentId: '2',
    professionalId: '1',
    professionalName: 'Dr. Roberto Almeida',
    date: '2025-10-05',
    rating: 4,
    comment: 'Ótimo profissional, mas o tempo de espera foi um pouco longo.',
    category: 'service',
  },
  {
    id: '11',
    patientId: '3',
    patientName: 'Pedro Henrique Silva',
    appointmentId: '3',
    professionalId: '2',
    professionalName: 'Dra. Fernanda Lima',
    date: '2025-10-02',
    rating: 5,
    comment: 'Resultados visíveis já nas primeiras sessões! Estou muito satisfeita.',
    category: 'professional',
  },
  {
    id: '12',
    patientId: '1',
    patientName: 'Lucas Oliveira Santos',
    appointmentId: '1',
    professionalId: '3',
    professionalName: 'Dra. Juliana Mendes',
    date: '2025-09-28',
    rating: 2,
    comment: 'Houve um mal-entendido na marcação da consulta. Precisamos melhorar a comunicação.',
    category: 'service',
  },
];

export const mockProgressReports: ProgressReport[] = [
  {
    id: '1',
    patientId: '1',
    professionalId: '4',
    professionalName: 'Dr. Carlos Eduardo',
    date: '2025-10-30',
    period: 'Setembro - Outubro 2025',
    achievements: [
      'Melhora na comunicação não-verbal',
      'Redução de comportamentos repetitivos',
      'Maior tempo de atenção em atividades dirigidas',
      'Iniciando contato visual espontâneo',
    ],
    challenges: [
      'Ainda apresenta dificuldade em ambientes com muitos estímulos',
      'Resistência a mudanças na rotina',
    ],
    nextSteps: [
      'Continuar terapia comportamental',
      'Introduzir atividades de grupo gradualmente',
      'Trabalhar habilidades sociais',
    ],
    overallProgress: 'good',
  },
  {
    id: '2',
    patientId: '2',
    professionalId: '2',
    professionalName: 'Dra. Fernanda Lima',
    date: '2025-10-28',
    period: 'Agosto - Outubro 2025',
    achievements: [
      'Aumento de 20% na amplitude de movimento dos membros inferiores',
      'Melhor controle postural',
      'Consegue manter-se em pé com apoio por 5 minutos',
    ],
    challenges: [
      'Espasticidade ainda presente nos períodos da manhã',
      'Fadiga muscular após exercícios prolongados',
    ],
    nextSteps: [
      'Intensificar exercícios de fortalecimento',
      'Avaliar possibilidade de órtese',
      'Manter frequência de 3x/semana',
    ],
    overallProgress: 'excellent',
  },
];